group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: DYDwnquZPsndWOAqEpbOeNLc9hHiVP6IBxXzrqLOiv2wtY3/C3yB7+Zw94QTge4M9JvO9aJ0G6Tq4g8PojlUhMsI1gFJe8DctXcx2GL3eTR7TFiaJW2dU4FdeLp3MRZ9A6rll2/0taStUYHBweUJEoT/7QHpIIYTI+C/0EDWGsQS4CWUbhzZns/oQmO4qr7s/43n5TXdoZbQsWvNe+uSu2KLV3tkejLmHmyCN17vR/8X6llToefSaVD7ZUXeTFhnIQlW/F5E9A5N2FcyGDG4rTGDXqr66DxfXKsWcpSwKFzOFUkwOdd7guu2qkzWemtPrDMPF6ixXehtS2WzzEACJ+W5kEhSGth+A8CYzR8y7D4JitUNv21xsNxqclJD5Ugw3BCXeNG+pV6jt2VeQsYe3M/HFK0PctCLphOugNc9RC1byjzFzon0kOJ+u9QNdDb4LOrnKS52gIHowzy59KFMGdWfNeb9f3UYW/I0oKaPi1Ean4zUO/J4IBdahP6cdJWHNgCOFcjAVJ5/receZrFfv+XHDosCNlGJCZ+0iT8bhHT4/RdHmTZsLy3lckJzuyn26pa/gzh4fS+8xxcSgg+qvR79XAGL4PecaSsUFmzeXcrDIX86xP4x03mSAMFlnpidJMaA9gGI7UU4tFFGADNh6DvqX1bEzfwT5tjjXA17rbM=
  - secure: o9QTBn7EqutCTNupWSocdVeLWuazBea9KwYLKH/tG1/0XrzXyfEi9+QJLFq6G2i8YzFQImGbt58HmAJimmHp4KI2Aa9g/E+ZuTF922Ar/asgHgotJ5fKcJCOk8ETOVMA74KfcREOZ2feZlPxCDXwiiG27a3nraXpMoDtIgORA2AYPvSjGnhG3O8mDkvwxioF7egTJwdSiSMstNQQokj9o6CyTlMASB6UYhlCFtmASxoxg7PBw4X8v+OyWc3kZ934uyiSgFP6Pb5ydADKvcdaT205dSbK5E6tB4Ct+tTNMerGfSxda11xbSvDiSwJjrQr8X8Z+k7bDpgZTyDu4bSn/U/LBDRChHUS5MlMtKBt296stIJ/KLs3s8bLTCx8XC+5SHOKoQNSaWTzg/Yw0uRl9/VLePfCiYeGQXAEx9dzEErXp1/vLMSR7mGYVzz2MZ3ICd1AjTt0/6wcw1CCAHmMJcdXDonlZVe9U/vW6S1j/XsxAoI6mMkJqY7vXzC9fSOuqIahMoLHgaZ/cyjR3G5JFgzPpto52poI40ox1fxm83eNxn2HeDfcd2qAliYltvLLJ9d/RxGunEqDVU7MKLy3YGZvFaS3BuVq8YJNG8g0JsXAsQ7SBzPt8rGXWwiHd7ddpiubbMAvDOieG0Gs/KCoq7eira+j5F9weUOU6AAEcB4=
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
