group: travis_latest
language: node_js
node_js: node
cache: yarn
deploy:
  provider: npm
  skip_cleanup: true
  'on':
    tags: true
  email:
    secure: >-
      gbFKi5bbl0MLsuEuWGEn6bSONEZF6g2hHUg3P73eQCyxNROtUkTx1CC6qXVIyIMdsPRkVX9iej2uy0Gtm6Otj4Mxjg2szO1ykk7WBVZUTxq9s4iHZwwKNtCio1sT41y+wsrflaUOnqljrj6s5PPe39Hj0VMj+T4wUG676P+T4/A9isI4v8TbDLWNJZysT7+1zuhRjpIF+leMzrTKQKQvCXw8TosXbF9QmCgMlirLwZPvHRrNT73YiYLMgtKYVPHDz31RgqVEwXmeaOoSK+Wcbh9Hm6lIDFtm2ykwwYHKI7OC6OoJ8e1CGFJFaW7lViQq5EAts2Wyff/and5IxZBPjAXkdOQnt+EaT1Q1rV6obpaYwHcp4f5XkrYBURL64bGfVd2DjUxcrhEVT37c8iPOP77jNx8a0z9+lwZT7CHuPXouvuth7bkFycAnqQLlMcBQeaDvygpyhWma05wIqOChK1KfzCqp45jnHV7sEszzZQaW7fW23GnubRzQ5w/s+sHCLIuQjIBj7Tf950eGqhGWaNckeM0Gmu7z5PbvifauBx05qLy0tWeUVpXqmqtm/171HFVzDNbMl1DcFstAdM20j+C2EVcMGqGLd/mc0esiHqnuwszjg2EK36NSb9SFCXtB41OZ3Gukfk3s+sZCSbB6kCsrKJhG2pydFvaoHW1q5RM=
  api_key:
    secure: >-
      Uahzzx/2futetr+kqwtKZaK147gtDqc6diw/pvp6zZ1yIZ92f28qs1yS4ZEqAoWsYRhkJc3fjlPiYyVDIt3UAhd5ORYm/x3nUmfCHR+8sLdb3ndrIMARKmBRtSp3s1fAg0YA+BgJ9k/MAkOnI4I+78oLGYUo70Vnz2DnxJ2AEF6UHZHGGrhECbvcv7RtCTQfzDquEUqGpcz7uGO1jN9uwT8dnYQclGQeIn+hN03rNF2TNCYeFuASuhQ6yDIEetOEn1UKG60vdRWXvhvjqnaSITW8T3yO/1SJQ5oDuzmxZmSgrI8LZcwDDsQaJDVSiIKmltZP+c4C9iMF3jaEZfXt+EIVHUBZBNFxy5jxKH7EuLz1sCXcR1oTLthfBmy0J5bwytqimxj2AKNIPIbVlc5tfKykPm9+x0DI+wmmGg5hllAde9ljhVtwcBVmfXLD7FKUzPhX6XyvrvIUM2VDNFaIMsyF29WjlynjsUOPrkavgXEdPDucd6QhW5os3Ltt33vyQExNWgtAXyZ+NUljsu80kbSHLfletz2fvU9Jdc+6+SaE0IEonBLqTUPYmUI1d0syiOfkSZ4X+r7cF7z1unxUFDlupFtJQJZDhBTRBm20nkLJATub23X9oeIaYeA0h5pcQ+bHLCPMWrykBqv6l7EMVHYc0+iKenknK4sjz4AuZ98=
