group: travis_latest
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: e3aj5v6DIFVTiQNEmndN+ue25iX1B9s1jSA/Wn4RqWpnbvQfdUuQ6S1L0ZlMz/RxPCUIEZYqGWzeK1UdXNb5fbCpsZmrMr+kUH/xjHULbX5b02VmkGOhqMFqVgpz6q18JiCTUEEbzONQP17tWbrYexBPyPwdODqaUYmGySQzS/BfzUx4rhuVZgmdaSObdnl0GwONBE00wLIDDEyn1OqLaDa/QJ6qobTlofGa7OzSzUAb0S0QRF1wG6qFAEZoIbB/TjsNfBgdQr4fuPEDHuWv/9i8pS6ZDyzOdGlsQZCBihgub7nwJE0Qd1S67Z9oEYOeZnbnwKQHvG33MepXaN3iOOnDaxEdeVmWpDkGUEQ1JIjFETyku9QJAQjd68dL31s4x7ryshaap8g8GN1r0lWEsW/jmbWZWWxUeHxvsStKl+x5LSD2pEazA7kvGnzGATZSlyMhtMYKb0Cnt+uLXNPYcrrHfxAVUQiFH2wXanFheudtvV86dYrJFwgwJ7T75YhrGTFpO97OHW16CM1LtL4Fg+6+AVuibVg848+Az5Cm6HOtBu6Wh7RmaH6DAPQFAn2PLnfOimxLJj8qrJ10PjCApvrBYEi9NAn3YQXexOcnQaay95cIdKNrbdjX1jEcODUWSmuKSJt+JX6OHOUyR5fVg8Ykdd1MHVAkyyg4xFunUSQ=
  - secure: lkHMV8NXX5bw3ZRFfEwutDoZWf6Cgy/a4AWnGGLOCQs3eWnmCFIBlUq5eQCy0/SP8tu/6h+M619QfUBl3B1YluPvX5KkZ3QAGSn8W2gdXeY1a6JYwLBcYHromMk2R+0u/wUBm7H26GhtTZGoXH3nmmn/TONsDthmB9WCpWjtm7V0OKZ4TjIuBInbjwPj11NHQ4bF+KA4rnxvZWNejEM/U2AVetGze5/v8T/pCNv9L7AH/h+CpWn50bVvMVq+H+BKVma43/TN2rdJ6ZBzmFijr6V2b80fv1STHDixEgXzz8SIhtM8qE8C1Uq8sSM+Flml5+Wek7I00DDWsWVzHnI+uzT5UBl0jFJmFSh4J9m21lGK9h57mvT8+xUimIwIsgN5ikFAi0FZn3vvxf4yRRfn3w/7P6SFiAvQOcu0uA7df5ThLY9lo0Nc1wRNPUNMFEPxouaw6Th2yycP4H9kykGmpv1GlWgcA6m6c2VblDoHb3IOpFs8jr5ztZEDpAxpmfaaX6cmKwAd5yaOGJIPxAd5h5YfHQsuNxSkJ+XK4cL2SvXP8tFxDkNl29z17HH+vbmlXgJbu+L+Tq/nPMFSIlC94tXSTKNRU0DfsPdJDsI1s8abSHaC275GVs6/OXhCV5BS7PBJc2hoiSms2mynj5k2NoPQOSbiV62Pnh9zHf2Ke3A=
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
