dist: xenial
addons:
  chrome: stable
language: node_js
node_js: node
cache: yarn
env:
  global:
  - secure: fmcXEsrGjgppMDxK8BQBSGsmo+/FSpRJvrIVWtpZ0N1R2mnxZTdidIHF7sA2iz+AtFGX42ncEE22Rv5/FoxZMuooyC/72AAOdM6d/pizTJRhYqQJgFCtSP0OuLh7uelTW4agSH7u4fMYzaVHSJeoLx8SmeAcx645ll3sII4XFg+FyP5FZYDlLaZrAP5vHzvHFQc1JzDnov/1sLeYbbrzUfFFeG5h3ZF2Xl9iRjoQeB5EXIAM9tg1zF600z3zeejizNYtRhI1QIOAkeNT/Nuvle0vRKlv9aLuKQZ99N4edYOUViQnc+YlWFgVC/LyKbYQQGEgSWnQLg4H2rkLWQUOhggny3cUbaZ2hS76J7dW9SIP4xSZ48GL124kKI/fOLrusCoKhMs5twghbPB3tIYe2D4N4DOrFnO5g8g+XfK7ImFvB99vxp7gepI6ZF29JD4tUg4PbcXjtlhTCtvUsGLy7WaWTiAeXJy5LG8gAqx6KkfvCZ8c8Znj60WRegMGm2IwoKcCH7ySuSZsK7ix78fNpB+gJiCV60XTHJFOMwYmdGtaLVc8qmqGlVFCsLG/b6XnCtir29fyiOg+EfF0SPiIZcCM39G/xoyileK7wYCh8q/be+61s8GXM2b7x8TwBuoZN6+JUoSOzOud6fX5hP3CchYOnrzXPqaEhKYYvKsm+8E=
  - secure: peFk1s+JjhIBryAucpcFVOTH1Sow8C+F86l5SGSbDMeWgjBqHbRexTnzNh7EbfKqzBmDy/Q2qJTWNcafR5Yvs+x260os1H2KAcbPAfOYB15+KKoklnqIu2B2OLWcXH92f8u0RGbEo+zNNUZ+kenIczU/yCz6zz1BkBXyDMGGZ5CDjT+uHRLfewOZsgA8XszSVyeBsV6vKg4mQX7O4wNouC/gczKARHbuanDrHJttpbwGW1ZKw1tcc4+7xNiNnhqNdnV8lkETlMON65eFSFbZHE0naDqaKW4HIMZUQ7c5FlEugPHpnmXYyLRWYxIrfw3+tcPv1lzTblBjlzTg7alUwQbJ63eI6g4/5tS/7F0dnulfPtogOGfvsT8+M0gHxuS7WweMaPp2u8ZyYyyZ0bRG8+3An9rog76JOn69u37qsszxVSzEGNsm/AQuvw6yaMSFKMk9OYksg5tUKNH1jW+ayn4Ltn3UkBFNS/VUyDxK4QTy94EaMh+OYWkxI9pKLcubpeSuZ0CrrnuRw9zz6Rr06+3b2nuZwZ24M+ue4Wxb3LuL+nEbCoq77AkSqyjtoZgCm5a5ocuL9aFBKkm1lQWqillp5QDzSU+F//Gdd8h1U4y2S4kTGg/jQzEzc82H+u1knsazHaga2LZ6MaF389CjIzw8lmnUV3zVg+IzzVycaTM=
deploy:
  provider: script
  skip_cleanup: true
  script:
  - yarn release
